/**
 * Generation worker.
 *
 * Owns the durable job queue and the real generation pipeline: claim a job from the database,
 * extract concepts with a provider, verify them against the stored source, decide each card's
 * format, validate every card, and persist the result. The API imports this package so the
 * preview runs the same code a standalone worker process would.
 *
 * This package is server-only. It holds the provider API key and reads the filesystem for prompts,
 * so it must never be imported by the browser bundle.
 */

export {
  DEFAULT_MAX_ATTEMPTS,
  JobCancelledError,
  JobClaimLostError,
  JobPausedError,
  LEASE_SECONDS,
  PENDING_CANCEL_MESSAGE,
  PENDING_PAUSE_MESSAGE,
  RETRY_BACKOFF_SECONDS,
  RESUME_ATTEMPT_ALLOWANCE,
  cancellationRequested,
  checkpointIdentityOf,
  claimIdentityOf,
  claimNextJob,
  enqueueGenerationJob,
  failJob,
  finaliseCancellation,
  finalisePause,
  finaliseWithPublication,
  recoverAbandonedStops,
  findJob,
  isJobCancelled,
  isJobClaimLost,
  isJobPaused,
  pauseRequested,
  readCheckpoint,
  readCoverageSummary,
  readSectionIds,
  recordJobProvider,
  recordJobRefusal,
  recordProviderAttempt,
  renewLease,
  requestCancellation,
  requestPause,
  requireJob,
  resumeJob,
  toContractJob,
  writeCheckpoint,
  type CancellationOutcome,
  type ClaimIdentity,
  type ClaimOptions,
  type CompleteInput,
  type EnqueueInput,
  type FailureInput,
  type FailureOutcome,
  type FinalisationOutcome,
  type GenerationJobRow,
  type PauseOutcome,
  type ProviderAttemptInput,
  type ResumeOutcome,
  type ResumeResult,
  type StoredResult,
} from './queue';

export {
  BudgetExceededError,
  DEFAULT_CHARS_PER_TOKEN,
  MAX_RESERVATION_OUTPUT_TOKENS,
  NOMINAL_JOB_CHARS,
  PRICE_TABLE_VERSION,
  assertBudgetHeadroom,
  costForTokens,
  estimateAttemptMinor,
  installationLimitMinor,
  isBudgetExceeded,
  periodKeyFor,
  readAccountingIncidents,
  readBudgetSnapshot,
  readLimits,
  readReconciliationAudit,
  readUncertainCharges,
  readUsageTotals,
  reconcileReservation,
  reserveBudget,
  resolvePricing,
  setInstallationLimit,
  settleReservation,
  type AccountingIncident,
  type AttemptCostBasis,
  type BudgetLimits,
  type BudgetRefusal,
  type BudgetSnapshot,
  type Pricing,
  type ReconcileResult,
  type UncertainCharge,
  type ReserveOutcome,
} from './budget';

export {
  CARD_BATCH_SIZE,
  CHECKPOINT_VERSION,
  HEARTBEAT_LEASE_FRACTION,
  MAX_CONCEPTS,
  MAX_REPAIR_ATTEMPTS,
  MAX_SOURCE_CHARS_PER_CALL,
  PIPELINE_VERSION,
  hasDeletableSpan,
  ocrPageLimit,
  planConceptBatches,
  runGenerationJob,
  type RunCheckpoint,
  type RunOptions,
  type RunOutcome,
} from './pipeline';

export {
  MAX_OCR_BYTES_PER_RUN,
  MAX_OCR_IMAGE_BYTES,
  MAX_OCR_PAGES_PER_RUN,
  OCR_CLAIM_STALE_MS,
  claimOcrPage,
  planPageOcr,
  readPageReading,
  storeOcrEmpty,
  storeOcrFailure,
  storeOcrRead,
  storeOcrUnavailable,
  type OcrCandidate,
  type OcrPlan,
  type OcrReading,
  type OcrReadingProvenance,
} from './ocr';

export {
  buildSectionScopes,
  expandSelectedSections,
  loadStoredSource,
  locateExcerpt,
  normalizeText,
  type SectionRow,
  type SectionScope,
  type SourceBlockRow,
  type SourceLocation,
  type StoredSource,
} from './source';

export {
  DEFAULT_POLL_INTERVAL_MS,
  GenerationWorker,
  type WorkerEvent,
  type WorkerEventType,
  type WorkerOptions,
} from './worker';
